name: Build and Deploy to Azure Container Apps (Dev)

on:
  push:
    branches:
      - dev

env:
  ACR_NAME: projectportfolioregistry
  IMAGE_NAME: portfolio.dev
  CONTAINER_APP_NAME: project-portfolio-dev-app
  RESOURCE_GROUP: project-portfolio-resource
  BASE_APPLICATION_URL: https://project-portfolio-dev-app.wittybay-0abce5d9.norwayeast.azurecontainerapps.io
  TENANT_NAME: digdir.no
  DRIVER: ODBC Driver 18 for SQL Server
  DATABASE: PortfolioWarehouse
  SCHEMA: "portfolio_dev"
  CLIENT_ID: ${{ secrets.CLIENT_ID }}
  TENANT_ID: ${{ secrets.TENANT_ID }}
  SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
  STORAGE_SECRET: ${{ secrets.STORAGE_SECRET }}
  SUPER_USER: ${{ secrets.SUPER_USER }}
  SERVER: ${{ secrets.SERVER }}
  CLIENT_SECRET_NAME: ${{ secrets.CLIENT_SECRET_NAME }}
  KEY_VAULT_URL: ${{ secrets.KEY_VAULT_URL }} 
  FABRIC_CLIENT_ID: ${{ secrets.FABRIC_CLIENT_ID }} 
  FABRIC_SECRET_NAME: ${{ secrets.FABRIC_SECRET_NAME }} 

permissions:
  id-token: write
  contents: read
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
      
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t $ACR_NAME.azurecr.io/$IMAGE_NAME:${{ github.sha }} .
          docker tag $ACR_NAME.azurecr.io/$IMAGE_NAME:${{ github.sha }} $ACR_NAME.azurecr.io/$IMAGE_NAME:latest

      - name: Login to ACR
        run: |
          az acr login --name $ACR_NAME

      - name: Push Docker image to ACR
        run: |
          docker push $ACR_NAME.azurecr.io/$IMAGE_NAME:${{ github.sha }}
          docker push $ACR_NAME.azurecr.io/$IMAGE_NAME:latest

      - name: Deploy to Azure Container Apps (dev)
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az account set --subscription ${{ secrets.SUBSCRIPTION_ID }}
            az containerapp update \
              --name $CONTAINER_APP_NAME \
              --resource-group $RESOURCE_GROUP \
              --image $ACR_NAME.azurecr.io/$IMAGE_NAME:${{ github.sha }} \
              --revision-suffix "build-${{ github.run_number }}" \
              --set-env-vars \
                BASE_APPLICATION_URL=${BASE_APPLICATION_URL} \
                SCHEMA=${SCHEMA} \
                TENANT_NAME=${TENANT_NAME} \
                DRIVER="${DRIVER}" \
                DATABASE=${DATABASE} \
                STORAGE_SECRET=${STORAGE_SECRET} \
                SUPER_USER=${SUPER_USER} \
                SERVER=${SERVER} \
                CLIENT_ID=${CLIENT_ID} \
                CLIENT_SECRET_NAME=${CLIENT_SECRET_NAME} \
                KEY_VAULT_URL=${KEY_VAULT_URL} \
                FABRIC_CLIENT_ID=${FABRIC_CLIENT_ID} \
                FABRIC_SECRET_NAME=${FABRIC_SECRET_NAME} \
                TENANT_ID=${TENANT_ID} \
                UUID_RUN=${{ github.run_id }} \
              --cpu 1 \
              --memory 2Gi
