name: Build and Deploy to Azure Container Apps (Dev)

on:
  push:
    branches:
      - dev

env:
  ACR_NAME: projectportfolioregistry
  IMAGE_NAME: portfolio.dev
  CONTAINER_APP_NAME: project-portfolio-dev-app
  RESOURCE_GROUP: project-portfolio-resource
  BASE_APPLICATION_URL: https://project-portfolio-dev-app.wittybay-0abce5d9.norwayeast.azurecontainerapps.io
  TENANT_NAME: digdir.no
  DRIVER: ODBC Driver 18 for SQL Server
  DATABASE: PortfolioWarehouse
  SCHEMA: "portfolio_dev"
permissions:
  id-token: write
  contents: read
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t $ACR_NAME.azurecr.io/$IMAGE_NAME:${{ github.sha }} .
          docker tag $ACR_NAME.azurecr.io/$IMAGE_NAME:${{ github.sha }} $ACR_NAME.azurecr.io/$IMAGE_NAME:latest

      - name: Login to ACR
        run: |
          az acr login --name $ACR_NAME

      - name: Push Docker image to ACR
        run: |
          docker push $ACR_NAME.azurecr.io/$IMAGE_NAME:${{ github.sha }}
          docker push $ACR_NAME.azurecr.io/$IMAGE_NAME:latest

      - name: Deploy to Azure Container Apps (dev)
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            az containerapp update \
              --name $CONTAINER_APP_NAME \
              --resource-group $RESOURCE_GROUP \
              --image $ACR_NAME.azurecr.io/$IMAGE_NAME:${{ github.sha }} \
              --revision-suffix "build-${{ github.run_number }}" \
              --set-env-vars "BASE_APPLICATION_URL=${BASE_APPLICATION_URL}" "SCHEMA=${SCHEMA}" \
              "DRIVER=${DRIVER}" "TENANT_NAME=${TENANT_NAME}" "DATABASE=${DATABASE}" "DRIVER=${DRIVER}" \
              "KEY_VAULT_URL=$${{ secrets.KEY_VAULT_URL }}" "CLIENT_ID=$${{ secrets.CLIENT_ID }}" "CLIENT_SECRET=$${{ secrets.CLIENT_SECRET }}" \
              "AZURE_TENANT_ID=$${{ secrets.FABRICS_CLIENT_ID }}" "uuid_run=$${{ secrets.UUID_RUN }}"
              --cpu 1 \
              --memory 2Gi
